### PR TITLE
change repo to gcr

### PR DESCRIPTION
**Pull request by tniita**
**Overview**
---
This pull request is for #4.

**Which file changed?**
---
`charts/oci-secrets-store-csi-driver-provider/values.yaml`

**What did you change?**
---
provider.image.repositry and tag.

**Why did you change it?**
---
This change will belong to users to enable to pull the provider image out-of-the-box.

### CODE REVIEW

**Comment by tniita** [comment]
@rajashekhargundeti 
Plaese review this pr.

**Comment by rajashekhargundeti** [comment]
Thank you for the PR.
Please check if the below fulfils your requirement:

```
helm repo add oci-provider https://oracle-samples.github.io/oci-secrets-store-csi-driver-provider/charts
helm install oci-provider oci-provider/oci-secrets-store-csi-driver-provider --namespace kube-system
```

**Comment by tniita** [comment]
@rajashekhargundeti 
Thanks for your checking!
I confirmed the pods were running by using command you provided and my source repo.

```sh
[opc@oci-tutorials-env oci-secrets-store-csi-driver-provider]$  kubectl get daemonset \
>       --namespace kube-system \
>       --selector='app.kubernetes.io/name in (oci-secrets-store-csi-driver-provider, secrets-store-csi-driver)'
NAME                                    DESIRED   CURRENT   READY   UP-TO-DATE   AVAILABLE   NODE SELECTOR            AGE
oci-provider-secrets-store-csi-driver   1         1         1       1            1           kubernetes.io/os=linux   3m30s
oci-secrets-store-csi-driver-provider   1         1         1       1            1           <none>                   3m30s
```

**Comment by rajashekhargundeti** [comment]
As the helm packaging in the plan and hardcoding the repo and tag in the values doesn't solve the problem. 
please let me know if we still require this PR.

**Comment by tniita** [comment]
@rajashekhargundeti 
That is true but I guess users may be confused the install process that there is the following statements.
> Default values are provided in charts/oci-secrets-store-csi-driver-provider/values.yaml file, can be overridden as per the requirement.

Users may want to know how to override the values.(of course, users can build image by themselves, but it's not easy for some users.)
So, it is better that we should notice users gcr image is available.
How about adding the example how to override the image field using gcr image in the get started document?
I will try it.

**Comment by rajashekhargundeti** [comment]
Done, Here you go: https://github.com/oracle-samples/oci-secrets-store-csi-driver-provider/blob/main/GettingStarted.md#helm-deployment

**Comment by tniita** [comment]
Thannks,
I confirmed it and I close this sr.

**Comment by daitangio** [comment]
This fix is still needed, because following the getting started, I was unable to install it with helm charts defaults... (I am using OKE on Oracle Cloud)
Can you provide **some oci-secrets-store-csi-driver-provider** repository examples?
I cannot find it on docker hub neither on iad.ocir.io.
What is the correct path inside iad.ocir.io (if any)?

**Pull request closed without merging**
